name: Backend API CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - 'prisma/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - 'prisma/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: 'api/package.json'
        
    - name: Install Root Prisma Client
      run: npm install @prisma/client --legacy-peer-deps
      
    - name: Install API dependencies
      working-directory: ./api
      run: npm install --legacy-peer-deps
      
    - name: Generate Prisma Client
      working-directory: ./api
      run: npx prisma generate --schema ../prisma/schema.prisma

    - name: Typecheck API
      working-directory: ./api
      run: npx tsc --noEmit
